// Class automatically generated by Dev-C++ New Class wizard

#include "classes.h" // class's header file
#include <iomanip>
// class constructor
classes::classes(char *s1,int n)
{
	numberOfStudents=n;
	strcpy(name,s1);
	studentList= (n>0) ? new student[n]:NULL;
}

// class destructor
classes::~classes()
{
	delete [] studentList;
}
istream &operator>>(istream &is,classes &obj){
	cout<<"Class name: ";
	is.getline(obj.name,6);
	cout<<"Number of student: ";
	is>>obj.numberOfStudents;
	obj.studentList= (obj.numberOfStudents>0) ? new student[obj.numberOfStudents]:NULL;
	fflush(stdin);
	if (obj.numberOfStudents) cout<<"Enter student list: "<<endl;
	for (int i=0;i<obj.numberOfStudents;i++){
		cout<<i+1<<","<<endl;
		is>>obj.studentList[i];
		}
	fflush(stdin);
	cout<<"Advisor: "<<endl;
	is>>obj.advisor;
	return is;
	};
ostream &operator<<(ostream &os,const classes &obj){
	os<<"Class name: "<<obj.name<<endl<<"Number of student: "<<obj.numberOfStudents<<endl;
	if (obj.numberOfStudents) 	os<<"Student list: "<<endl;
	for (int i=0;i<obj.numberOfStudents;i++){
		os<<i+1<<","<<endl;
		os<<obj.studentList[i]<<endl;
		}
	fflush(stdin);
	cout<<"Advisor: "<<endl;
	os<<obj.advisor;
	return os;
	};

