// Class automatically generated by Dev-C++ New Class wizard

#include "teacher.h" // class's header file

// class constructor
teacher::teacher(char *s1,char *s2,int age,char *s3):person(s1,s2,age)
{
	strcpy(rank,s3);
}

// class destructor
teacher::~teacher()
{
	// insert your code here
}
istream &operator>>(istream &is,teacher &obj){
	is>>(person &)obj;
	fflush(stdin);
	cout<<"Rank: ";
	is.getline(obj.rank,10);
	fflush(stdin);
	return is;
	};
ostream &operator<<(ostream &os,const teacher &obj){
	os<<(person &)obj<<endl<<"Rank: "<<obj.rank;
	return os;
	};
