// Class automatically generated by Dev-C++ New Class wizard

#ifndef CLASSES_H
#define CLASSES_H

/*
 * Author: Kem
 * Bai 4 Thuc hanh OOP
 */
#include <iostream>
#include <string.h>
#include <stdlib.h>
#include "student.h"
#include "teacher.h"
using namespace std;
class classes
{
	private:
		char name[6];
		int numberOfStudents;
		student *studentList;
		teacher advisor;
	public:
		// class constructor
		classes(char *s1="",int n=0);
		// class destructor
		~classes();
		friend istream &operator>>(istream &,classes &);
		friend ostream &operator<<(ostream &,const classes &);
};

#endif // CLASSES_H
