// Class automatically generated by Dev-C++ New Class wizard

#include "person.h" // class's header file

// class constructor
person::person(char* s1,char* s2, int age)
{
	strcpy(name,s1);
	strcpy(address,s2);
	this->age=age;
}

// class destructor
person::~person(){}

istream &operator>>(istream &is,person &obj){
	cout<<"Name: ";
	is.getline(obj.name,30);
	cout<<"Address: ";
	is.getline(obj.address,50);
	cout<<"Age: ";
	is>>obj.age;
	fflush(stdin);	
	return is;
	};
ostream &operator<<(ostream &os,const person &obj){
	os<<"Name: "<<obj.name<<endl<<"Address: "<<obj.address<<endl<<"Age: "<<obj.age;
	return os;
	};
