// Class automatically generated by Dev-C++ New Class wizard

#ifndef STUDENT_H
#define STUDENT_H

#include "person.h" // inheriting class's header file

/*
 * Author: kem
 */
#include <iostream>
#include <string.h>
using namespace std;
class student : public person
{	
	private:
		char className[6];
	public:
		// class constructor
		student(char *s1="",char *s2="",int age=0,char *s3="");
		// class destructor
		~student();
		friend istream &operator>>(istream &,student &);
		friend ostream &operator<<(ostream &,const student &);		
};

#endif // STUDENT_H
