// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEACHER_H
#define TEACHER_H

#include "person.h" // inheriting class's header file

/*
 * No description
 */
#include <iostream>
#include <string.h>
using namespace std;
class teacher : public person
{	private:
		char rank[10];
	public:
		// class constructor
		teacher(char *s1="",char *s2="",int age=0,char *s3="");
		// class destructor
		~teacher();
		friend istream &operator>>(istream &,teacher &);
		friend ostream &operator<<(ostream &,const teacher &);		
};

#endif // TEACHER_H
