// Class automatically generated by Dev-C++ New Class wizard

#ifndef BINARY_H
#define BINARY_H

// Class Binary
// Author: Kem
#include <iostream>
#include <stdlib.h>

#define MAXBIT sizeof(int)*2

using namespace std;

class binary
{	private:
	int realSize;
	const int size;
	char *bit;	
	public:
		// class constructor
		binary(int=0);
		binary(const char *);
		binary(const binary &);
		// class destructor
		~binary();
		int RealSize();
		const binary &operator=(const binary &);
		binary operator+(const binary &)const;
		binary operator-(const binary &)const;
		binary operator*(const binary &)const;
		binary operator/(const binary &)const;
		binary operator&(const binary &)const;
		binary operator|(const binary &)const;		
		binary operator^(const binary &)const;
		binary operator~(void);
		binary operator>>(int) const;
		binary operator<<(int) const;
		char &operator[](int) const;
		friend ostream &operator<<(ostream &,const binary &);
		friend istream &operator>>(istream &,binary &);		
		operator int()const;//Operator typecast from int to binary
};

#endif // BINARY_H
