// Class automatically generated by Dev-C++ New Class wizard

#include "complex.h" // class's header file

// class constructor
complex::complex(double r,double i):img(i),rea(r){}

// class destructor

complex::~complex(){}

//Method display on console screen a number complex
void complex::Print() const{
	cout<<endl<<rea<<"+"<<img<<"i";
	}
//Method addition number complex	
complex complex::Add(const complex &obj){
	return complex(rea + obj.rea,img + obj.img);
	}
//Method subtraction
complex complex::Sub(const complex &obj){
	return complex(rea - obj.rea,img - obj.img);
	}
//Method set value for the member of class
void complex::Set(double rea,double img){
	this->rea=rea;
	this->img=img;
	}
