// Class automatically generated by Dev-C++ New Class wizard

#ifndef DATE_H
#define DATE_H
// Author: Kem
// Bai 1.2
// ThOOP
class date
{	
	private:
		int day,month,year;
	public:
		//constructor with 3 argument to init specifically date
		date(int=1,int=1,int=1900);
		// class destructor
		~date();
		int GetDay() const;
		int GetMonth() const;
		int GetYear() const;
		bool IsLeapYear(int) const;
		bool IsLeapYear() const;
		int MonthDays(int =0,int =-1) const;
		bool Valid(int,int,int) const;// Validate a date
		void Print() const;
		bool SetDay(int);
		bool SetMonth(int);
		bool SetYear(int);
		bool SetDate(int,int,int);
		int NextDay();
		int PrevDay();
};

#endif // DATE_H
