// Class automatically generated by Dev-C++ New Class wizard

#ifndef MATRIX_H
#define MATRIX_H

/*
 * Class Matrix
 * Author: Kem
 */
 #include <iostream>
using namespace std;
class matrix
{
	protected:
		const int n,m;
		int v;
		float *arr;
		static int id;
	public:
		// class constructor
		matrix(int ,int );
		// class destructor
		~matrix();
		matrix(const matrix &);
		const matrix operator=(const matrix &);
		matrix operator+(const matrix &) const;		
		matrix operator-(const matrix &) const;
		matrix operator*(float) const;
		matrix operator*(const matrix&) const;
		friend matrix operator*(float,const matrix &);
		friend istream &operator>>(istream &,matrix &);
		friend ostream &operator<<(ostream &,const matrix &);
		float &operator[](int)const;		
		float &operator()(int,int)const;
		float operator~()const;
		static int ID(){ return id;};					
};

#endif // MATRIX_H
