// Class automatically generated by Dev-C++ New Class wizard

#include "node.h" // class's header file
#include <iostream>
#include <stdlib.h>
// class constructor
int node::count=0;
node::node()
{
	next=NULL;
	item=0;
	count++;
	id=count;
}
node::node(const node &obj){
	id++;
	item=obj.item;
	next=obj.next;
	}
// class destructor
node::~node()
{
	count--;
}
int node::SetItem(int v){
	item=v;
	return v;
	}
int node::GetItem()const{
	return item;
	}
node *node::GetNext()const{
	return next;
	}
node *node::SetNext(node *obj){
	next=obj;
	return obj;
	}
void node::Print()const{
	std::cout<<id<<":"<<item;
	}
