// Class automatically generated by Dev-C++ New Class wizard

#ifndef POLYNOMIAL_H
#define POLYNOMIAL_H

#include "vector.h" // inheriting class's header file
#include<iostream>
using namespace std;
/*
 * Author: Kem
 */
class polynomial : public vector
{
	public:
		// class constructor
		polynomial(int );
		// class destructor
		~polynomial();
		float operator()(int)const;
		friend istream &operator>>(istream &,polynomial &);
		friend ostream &operator<<(ostream &,const polynomial &);
};

#endif // POLYNOMIAL_H
