// Class automatically generated by Dev-C++ New Class wizard

#include "polynomial.h" // class's header file
#include <math.h>
#include <iomanip>
// class constructor
polynomial::polynomial(int n):vector(n+1){}

// class destructor
polynomial::~polynomial(){}
istream &operator>>(istream &is,polynomial &obj){
	for (int i=0;i<obj.n;i++){
		cout<<"he so x"<<i<<"= ";
		is>>obj[i];
		}
	return is;	
	};
ostream &operator<<(ostream &os,const polynomial &obj){
	os<<" f(x) = ";
	for(int i=obj.n-1;i>0;i--){
		os<<setprecision(3)<<obj[i]<<"x^"<<i<<" + ";
		} 
	os<<obj[0];	
	return os;	
	};
float polynomial::operator()(int x0)const{
	float t=0;
	for(int i=0;i<n;i++) t+=arr[i]*pow(x0,i);
	return t;
	};
