// Class automatically generated by Dev-C++ New Class wizard

#ifndef SET_H
#define SET_H

/*
 * Author: Kem
 */
class set
{
	public:
		// class constructor
		set();
		// class destructor
		~set();
};

#endif // SET_H
