// Class automatically generated by Dev-C++ New Class wizard

#ifndef STACK_H
#define STACK_H
// Author: Kem
// Bai 2.1 
// Bai 2.2
#include<iostream>
#include <stdlib.h>
#include "node.h"
using namespace std;
class stack
{	private:
		int size;
		const int maxSize;
		node *top;
	public:
		// class constructor
		stack(int=0);
		stack(const stack &);
		// class destructor
		~stack();
		void Pus(int);
		int Pop();
		bool IsEmpty() const;
		bool IsFull() const;
		int NumOfElement() const;
		void Print()const;		
};

#endif // STACK_H
