// Class automatically generated by Dev-C++ New Class wizard

#ifndef VECTOR_H
#define VECTOR_H
#include <iostream>
#include <stdlib.h>
using namespace std;
// Bai 3
// Author: Kem
 #include <iostream>
 using namespace std;
class vector
{
	protected:
		const int n;
		float *arr;
		static int id;
	public:
		// class constructor
		vector(int);
		// class destructor
		~vector();
		vector(const vector &);
vector operator=(const vector &);
		const vector operator+=(const vector &);		
		vector &operator+(const vector &) const;		
		vector operator-(const vector &) const;
		vector operator*(float) const;
		float operator*(const vector&) const;
		friend vector operator*(float,const vector &);
		friend istream &operator>>(istream &,vector &);
		friend ostream &operator<<(ostream &,const vector &);
		float &operator[](int) const;
		float operator~()const;
		static int ID(){ return id;};
		
};

#endif // VECTOR_H
