// Class automatically generated by Dev-C++ New Class wizard

#ifndef COMPLEX_H
#define COMPLEX_H
#include <iostream>
using namespace std;

// Author: Kem

class complex
{
	public:
		// class constructor
		complex(double =0, double=0); // Constructor cast type
		// class destructor
		~complex();
		complex Sub(const complex &);
		complex Add(const complex &);
		void Print(void) const;
	private:
		double rea, img;
		void Set(double=0,double=0);
};

#endif // COMPLEX_H
