// Class automatically generated by Dev-C++ New Class wizard

#ifndef MYSTRING_H
#define MYSTRING_H

/*
 * Author: Kem
 */
#define MAXLEN 256
 #include <iostream>
 using namespace std;
class MyString
{	private:
		int length;
		const int max;
		char *s;
	public:
		// class constructor
		MyString(char *s="");
		MyString(const MyString &);
		// class destructor
		~MyString();
		int Length(){return length;};
		MyString operator=(const MyString &);
		MyString operator+(const MyString &) const;
		MyString operator&(const MyString &) const;
		bool operator==(const MyString &)const;
		bool operator!=(const MyString &) const;
		bool operator>(const MyString &) const;
		bool operator>=(const MyString &) const;
		bool operator<(const MyString &) const;
		bool operator<=(const MyString &) const;
		friend istream &operator>>(istream &,MyString &);
		friend ostream &operator<<(ostream &,const MyString &);
		char &operator[](int)const;
		operator char*()const;//cast type from MyString to char *
};

#endif // MYSTRING_H
