// Class automatically generated by Dev-C++ New Class wizard

#include "set.h" // class's header file

// class constructor
set::set()
{
	// insert your code here
}

// class destructor
set::~set()
{
	// insert your code here
}
