// Class automatically generated by Dev-C++ New Class wizard

#ifndef POLYNOMIAL_H
#define POLYNOMIAL_H

#include "vector.h" // inheriting class's header file
#include<iostream>
using namespace std;
/*
 * Author: Kem
 */
 template <class T>
class polynomial : public vector<T>
{
	public:
		// class constructor
		polynomial(int );
		// class destructor
		~polynomial();
		float operator()(int)const;
		template<class S>
		friend istream &operator>>(istream &,polynomial<S> &);
		template<class S>		
		friend ostream &operator<<(ostream &,const polynomial<S> &);
};
#include "polynomialcpp.h"
#endif // POLYNOMIAL_H
